# Generated by Django 2.1.2 on 2020-06-15 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200615_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matillionjobinformation',
            name='LastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
