# Generated by Django 2.1.2 on 2020-06-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200615_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matillionjobinformation',
            name='LastModified',
            field=models.CharField(default='<function now at 0x0000029DC65DF730>/', max_length=400),
        ),
    ]
