# Generated by Django 2.1.2 on 2020-06-15 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200615_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='talendjobinformations',
            name='LastModifiedBy',
            field=models.CharField(default='--', max_length=400),
        ),
        migrations.AlterField(
            model_name='matillionjobinformation',
            name='LastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='talendjobinformations',
            name='LastModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
